package firewall

import "testing"

func TestParseIPTablesSave(t *testing.T) {
	sample := `# Generated by iptables-save v1.8.7
*filter
:INPUT ACCEPT [0:0]
-A INPUT -s 1.2.3.4/32 -p tcp -m tcp --dport 22 -m comment --comment "portpass:42" -j ACCEPT
-A INPUT -s 10.0.0.0/8 -p udp -m udp --dport 5000 -m comment --comment "portpass:7" -j ACCEPT
-A INPUT -s 8.8.8.8/32 -p tcp -m tcp --dport 80 -j ACCEPT
COMMIT
`
	got := parseIPTablesSave(sample)
	if len(got) != 2 {
		t.Fatalf("expected 2 portpass rules, got %d", len(got))
	}
	if got[0].RuleID != 42 || got[0].Port != 22 || got[0].Protocol != "tcp" || got[0].SourceIP != "1.2.3.4/32" {
		t.Errorf("rule[0] mismatch: %+v", got[0])
	}
	if got[1].RuleID != 7 || got[1].Port != 5000 || got[1].Protocol != "udp" {
		t.Errorf("rule[1] mismatch: %+v", got[1])
	}
}

func TestCommentTagRoundTrip(t *testing.T) {
	tag := CommentTag(1234)
	if tag != "portpass:1234" {
		t.Fatalf("unexpected tag %q", tag)
	}
	id, ok := ParseCommentTag(tag)
	if !ok || id != 1234 {
		t.Fatalf("ParseCommentTag(%q) = (%d, %v)", tag, id, ok)
	}
	if _, ok := ParseCommentTag("something-else"); ok {
		t.Fatal("ParseCommentTag should reject non-portpass comments")
	}
}

func TestExpandProto(t *testing.T) {
	cases := map[string][]string{
		"tcp":  {"tcp"},
		"udp":  {"udp"},
		"both": {"tcp", "udp"},
		"":     {"tcp"},
	}
	for in, want := range cases {
		got := expandProto(in)
		if len(got) != len(want) {
			t.Errorf("expandProto(%q) = %v; want %v", in, got, want)
			continue
		}
		for i := range got {
			if got[i] != want[i] {
				t.Errorf("expandProto(%q)[%d] = %q; want %q", in, i, got[i], want[i])
			}
		}
	}
}

func TestCanonicalSource(t *testing.T) {
	cases := map[string]string{
		"0.0.0.0/0":  "",
		"::/0":       "",
		"":           "",
		"1.2.3.4/32": "1.2.3.4/32",
		"   ":        "",
	}
	for in, want := range cases {
		if got := canonicalSource(in); got != want {
			t.Errorf("canonicalSource(%q) = %q; want %q", in, got, want)
		}
	}
}
